version: '3'
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - 9042:9042
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: localpostgresdb
  kafka:
    image: spotify/kafka
    container_name: kafka
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: localmongodb
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: localmysqldb
      MYSQL_USER: sa
      MYSQL_PASSWORD: secret